/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.wne;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int confirm=0x7f06000d;
        public static final int maptag=0x7f060012;
        public static final int restM=0x7f060003;
        public static final int restM1=0x7f060004;
        public static final int restM2=0x7f060005;
        public static final int restaurant=0x7f060010;
        public static final int restaurantDir=0x7f060002;
        public static final int restaurantDs=0x7f060001;
        public static final int restaurant_name=0x7f060000;
        public static final int restauranttag=0x7f060011;
        public static final int text1=0x7f06000e;
        public static final int title=0x7f060006;
        public static final int userTagD1=0x7f06000a;
        public static final int userTagD2=0x7f06000b;
        public static final int userTagD3=0x7f06000c;
        public static final int userTagList=0x7f06000f;
        public static final int userTagM=0x7f060007;
        public static final int userTagM1=0x7f060008;
        public static final int userTagM2=0x7f060009;
    }
    public static final class layout {
        public static final int restaurant_show=0x7f030000;
        public static final int usertag_edit=0x7f030001;
        public static final int usertag_list=0x7f030002;
        public static final int usertag_row=0x7f030003;
        public static final int wne_main=0x7f030004;
    }
    public static final class raw {
        public static final int proyecto1000=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int body=0x7f050002;
        public static final int confirm=0x7f050003;
        public static final int delete=0x7f050004;
        public static final int map=0x7f050011;
        public static final int newTag=0x7f050005;
        public static final int restaurant=0x7f05000e;
        public static final int restaurantDir=0x7f050010;
        public static final int restaurantDs=0x7f05000f;
        public static final int title=0x7f050001;
        public static final int userTagActivate=0x7f05000d;
        public static final int userTagD1=0x7f050009;
        public static final int userTagD2=0x7f05000a;
        public static final int userTagD3=0x7f05000b;
        public static final int userTagList=0x7f05000c;
        public static final int userTagM=0x7f050006;
        public static final int userTagM1=0x7f050007;
        public static final int userTagM2=0x7f050008;
    }
}
